class ChannelMethods{
  static String LOCATION_SERVICE_START  = "LOCATION_SERVICE_START";
  static String LOCATION_SERVICE_STOP   = "LOCATION_SERVICE_STOP";
  static String LOCATION_SERVICE_STATUS = "LOCATION_SERVICE_STATUS";
  static String LOCATION_SERVICE_META   = "LOCATION_SERVICE_META";  
}

