enum CallMethods {
    static let LOCATION_SERVICE_START  = "LOCATION_SERVICE_START"
    static let LOCATION_SERVICE_STOP   = "LOCATION_SERVICE_STOP"
    static let LOCATION_SERVICE_STATUS = "LOCATION_SERVICE_STATUS"
    static let LOCATION_SERVICE_META   = "LOCATION_SERVICE_META"
}